import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { liveQuery } from 'dexie';
import { MessageService } from 'primeng/api';
import { ReplaySubject, Subject } from 'rxjs';
import { SerialQRProject, SerialQrProjectMetadata } from 'src/utils/data';
import { db } from 'src/utils/db';

@Injectable({
  providedIn: 'root'
})
export class ProjectService {
  activeProject: SerialQRProject;
  readonly regenerateEvent: Subject<void> = new Subject();
  readonly onLoaded: ReplaySubject<SerialQRProject> = new ReplaySubject();
  showEdit = false;

  metadata: SerialQrProjectMetadata[] = [];

  constructor(private router: Router, private messageService: MessageService) {
    this.activeProject = this.generateNew({ name: 'AUTOGENERATED' });
    liveQuery(() => db.metadata.toArray()).subscribe(
      (metadata) => (this.metadata = metadata)
    );
  }

  regenerate() {
    this.regenerateEvent.next();
  }

  getLastViewed() {
    const lastViewed = localStorage.getItem('serialqr.lastviewed');
    if (lastViewed) {
      try {
        return parseInt(lastViewed);
      } catch (e) {
        return 1;
      }
    } else {
      return 1;
    }
  }

  openLastViewed() {
    this.open(this.getLastViewed(), true);
  }

  async open(id: string | number, redirect: boolean) {
    if (typeof id === 'string') {
      try {
        id = parseInt(id);
      } catch (e) {
        id = this.getLastViewed();
      }
    }
    const projectData = await db.projects.get(id);
    if (projectData) {
      if (projectData.serialQRVersion === 1) {
        this.activeProject = projectData;
      } else {
        id = await db.metadata.add({ name: 'AUTOCREATED' });
        await db.metadata.update(id, { name: `Unbenannt (${id})` });
        this.activeProject = this.generateNew(
          (await db.metadata.get(id)) as SerialQrProjectMetadata
        );
        await db.projects.put(this.activeProject, id);
        redirect = true;
      }
    } else {
      id = await db.metadata.add({ name: 'AUTOCREATED' });
      await db.metadata.update(id, { name: `Unbenannt (${id})` });
      this.activeProject = this.generateNew(
        (await db.metadata.get(id)) as SerialQrProjectMetadata
      );
      await db.projects.put(this.activeProject, id);
      redirect = true;
    }
    localStorage.setItem('serialqr.lastviewed', `${id}`);
    this.regenerate();
    this.onLoaded.next(this.activeProject);
    if (redirect) {
      this.router.navigate(['project', id, 'edit']);
    }
  }

  save() {
    db.metadata.put(this.activeProject.metadata, this.activeProject.id);
    db.projects.put(this.activeProject, this.activeProject.id);
    this.messageService.add({
      severity: 'success',
      summary: 'Projekt gespeichert',
      detail: 'Du kannst es beim nächsten mal wiederverwenden!'
    });
  }

  generateNew(metadata: SerialQrProjectMetadata): SerialQRProject {
    return {
      serialQRVersion: 1,
      id: metadata.id ? metadata.id : 9999,
      metadata,
      options: {
        print: 'paper',
        margin: {
          top: 10,
          bottom: 10,
          left: 15,
          right: 15
        },
        mergeSameCreditors: true,
        creditor: {
          iban: 'CH5204835012345671000',
          name: 'Firma Muster',
          zipAndPlace: '6000 Luzern',
          country: 'CH'
        },
        debtor: {
          name: 'Familie {Nachname}',
          address: '{Adresse}',
          zipAndPlace: '{PLZ} {Ort}',
          country: 'CH'
        },
        logo: {
          height: 30,
          width: 30,
          location: 'right',
          src: `${location.protocol}//${location.host}/assets/icons/icon-512x512.png`,
          correctionX: 2.9,
          correctionY: 2.9
        },
        headingLocation: 'left',
        headingSize: 9,
        customHeading: [
          { insert: 'Firma Muster', attributes: { bold: true } },
          { insert: '\nMax Muster\nMusterstrasse 35\n6000 Luzern' }
        ],
        addressLocation: 'right',
        showSenderAddress: true,
        addressSize: 10,
        dateFormat: 'long',
        place: 'Luzern',
        title: 'Rechnung für Produkt 25 an {Spitzname ?: Vorname}',
        titleSize: 11,
        textSize: 10,
        textBeforeTable: [
          {
            insert:
              'Liebe Familie {Nachname}\n\nVielen Dank für Ihren Auftrag, welchen ich folgendermassen verrechne:'
          }
        ],
        dataFiles: [
          {
            src: `${location.protocol}//${location.host}/assets/data/sample.xlsx`,
            content: [
              {
                Nachname: 'Meier',
                Vorname: 'Urs',
                Spitzname: 'Ürsu',
                Adresse: 'Kaspergasse 13',
                PLZ: '3525',
                Ort: 'Kasperhausen'
              },
              {
                Nachname: 'Meier',
                Vorname: 'Ursula',
                Spitzname: 'Ursi',
                Adresse: 'Kaspergasse 13',
                PLZ: '3525',
                Ort: 'Kasperhausen'
              },
              {
                Nachname: 'Müller',
                Vorname: 'Kari',
                Spitzname: '',
                Adresse: 'Müllerstrasse 36',
                PLZ: '8256',
                Ort: 'Müllersheim'
              }
            ],
            positions: [
              {
                designation: 'Produkt 25',
                count: '2',
                amount: '100'
              },
              {
                designation: 'Versand',
                amount: '5'
              }
            ]
          }
        ],
        tableTemplate: {
          header: {
            size: 8,
            bold: true,
            italic: false,
            background: '#c8c8c8'
          },
          body: {
            size: 8,
            bold: false,
            italic: false,
            background: '#ffffff'
          },
          footer: {
            size: 8,
            bold: true,
            italic: false,
            background: '#e0e0e0'
          },
          padding: {
            top: 2,
            left: 2,
            right: 2,
            bottom: 2
          },
          striped: true,
          showFooter: true,
          showPositionNr: true,
          showLines: false
        },
        textAfterTable: [
          {
            insert: 'Zahlbar innert '
          },
          { insert: '30', attributes: { bold: true } },
          {
            insert: ' Tagen.\n\nFreundliche Grüsse\n\n'
          },
          { insert: 'Max Muster', attributes: { bold: true } },
          { insert: '\nGeschäftsleiter Firma Muster' }
        ],
        message: 'Produkt 25 {Nachname} {Vorname}'
      }
    };
  }
}
