name: build

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ['Dependabot auto-merge']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: |
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Build App
        run: npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lucbu01/serial-qr:latest
