name: 'check pull request'

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: |
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: yarn install
        with:
          cmd: install
      - name: Build App
        run: npm run build
